platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'WPAppKit_Example' do
  pod 'WPAppKit', :path => '../'
#    pod 'WPAppKit', '1.0.1'
end
